name: Server CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Build Server with Maven
      run: mvn -B package --file Server/backend/pom.xml
      
    - name: Upload JAR file as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: server-jar
        path: Server/backend/target/boltech-0.0.1-SNAPSHOT.jar
      
  deploy:
    needs: build
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: server-jar
      - name: Move JAR file to target directory
        run: |
          ls -alh
          mv *.jar Server/backend/target/boltech-0.0.1-SNAPSHOT.jar
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run:  |
          cd Server
          ls -alh
          flyctl deploy --remote-only -a backend-boltech
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          OPENAI_API_KEY: ${{ env.API_KEYS_OPENAI_API_KEY }}
          LLAMA_API_KEY: ${{ env.API_KEYS_LLAMA_API_KEY }}
